In [1]:
import dynet as dy
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])

See https://github.com/clab/dynet/blob/ddc9253bdc39d2d17b583d9809d08d0835b13f44/pyexamples/tutorials/API.ipynb

# Creating Vectors

`dynet` `vector` objects can be created from `numpy` `array`s.

In [3]:
vector_a = dy.vecInput(4)
vector_a.set(a)

vector_b = dy.vecInput(4)
vector_b.set(b)

print("a", vector_a.npvalue())
print("b", vector_b.npvalue())

('a', array([ 1.,  2.,  3.,  4.]))
('b', array([ 9.,  8.,  7.,  6.]))


# Creating Matrices

`dynet` `matrix` objects must be created from a flat `python` `list`

In [4]:
sentence = dy.matInput(4,3)
sentence.set([1,9,5,5,2,8,5,5,3,7,5,5])
sentence.npvalue()

array([[ 1.,  2.,  3.],
       [ 9.,  8.,  7.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

# Convolutional Network Structures

$arg_1 \in R^{d,s}$ where $d$ is dimension of word vectors and $s$ is length of sentence <br>
$arg_2 \in R^{d,m}$ where $d$ is dimension of word vectors and $m$ is desired dimension of convolution

## Convolutions

In [22]:
z = [1] * 8
zz = [2] * 8

In [23]:
filter_z = dy.matInput(4,2)
filter_z.set(zz)
filter_z.npvalue()

array([[ 2.,  2.],
       [ 2.,  2.],
       [ 2.,  2.],
       [ 2.,  2.]])

In [24]:
# filter of height 2
# narrow means there is no padding
# dimension 1 is the dot product of sentence 1 and sentence 2
# dimension 2 is the dot product of sentence 2 and sentence 3
e = dy.conv1d_narrow(sentence, filter_z)
e.npvalue()

array([[  6.,  10.],
       [ 34.,  30.],
       [ 20.,  20.],
       [ 20.,  20.]])

In [25]:
# filter of height 2
# wide means there *is* padding
# dimension 1 is the dot product of <pad> and sentence 1
# dimension 2 is the dot product of sentence 1 and sentence 2
# dimension 3 is the dot product of sentence 3 and sentence 4
# dimension 4 is the dot product of sentence 4 and <pad>
e2 = dy.conv1d_wide(sentence, filter_z)
e2.npvalue()

array([[  2.,   6.,  10.,   6.],
       [ 18.,  34.,  30.,  14.],
       [ 10.,  20.,  20.,  10.],
       [ 10.,  20.,  20.,  10.]])

## Filters

What is the difference between `filter` and `conv`?

In [18]:
# this results in the sum of all elements in each dimension of the output of conv1d_narrow()
e3 = dy.filter1d_narrow(sentence, filter_z)
e3.npvalue()

array([[ 40.,  40.]])

In [19]:
# "wide" doesn't exist
e4 = dy.filter1d_wide(sentence, filter_z)
e4.npvalue()

AttributeError: 'module' object has no attribute 'filter1d_wide'

## Pooling

In [16]:
e5 = dy.kmax_pooling(sentence, 1)
e5.npvalue()

array([[ 3.],
       [ 9.],
       [ 5.],
       [ 5.]])

In [21]:
# when using k > 1, k @ 1 is the furthest right column
e6 = dy.kmax_pooling(sentence, 2)
e6.npvalue()

array([[ 2.,  3.],
       [ 9.,  8.],
       [ 5.,  5.],
       [ 5.,  5.]])